/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  Designguidelines: [{type: 'autogenerated', dirName: 'Designguidelines'}],  // foldername
  smarteditor: [{type: 'autogenerated', dirName: 'smarteditor'}],  // foldername
  flutter: [{type: 'autogenerated', dirName: 'flutter'}],  // foldername
  react: [{type: 'autogenerated', dirName: 'react'}],  // foldername
  ios: [{type: 'autogenerated', dirName: 'ios'}],  // foldername
  node: [{type: 'autogenerated', dirName: 'node'}],  // foldername
  laravel: [{type: 'autogenerated', dirName: 'laravel'}],  // foldername
  reactadminpanel: [{type: 'autogenerated', dirName: 'reactadminpanel'}],  // foldername
  android: [{type: 'autogenerated', dirName: 'android'}],  // foldername
  appresources: [{type: 'autogenerated', dirName: 'appresources'}],  // foldername
  // docs: [
  //   'getting-familiar-with-smart-editor',
  //   {
  //     type: 'category',
  //     label: 'Getting Started',
  //     link: {
  //       type: 'generated-index',
  //     },
  //     collapsed: false,
  //     items: [
  //       'getting-familiar-with-smart-editor/navigation',
  //     ],
  //   },
  // ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
